-- Drop tables in reverse dependency order (for clean re-runs)
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS member;

-- member
CREATE TABLE member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255)  NOT NULL UNIQUE,
    password   VARCHAR(255)  NOT NULL,
    name       VARCHAR(100)  NOT NULL,
    phone      VARCHAR(20),
    address    VARCHAR(500),
    role       VARCHAR(10)   NOT NULL DEFAULT 'USER',
    active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- product
CREATE TABLE product (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255)   NOT NULL,
    description    VARCHAR(2000),
    price          DECIMAL(19,2)  NOT NULL,
    stock_quantity INTEGER        NOT NULL DEFAULT 0,
    category       VARCHAR(100),
    image_url      VARCHAR(500),
    status         VARCHAR(10)    NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- cart (one per member)
CREATE TABLE cart (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT    NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES member(id)
);

-- cart_item
CREATE TABLE cart_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT    NOT NULL,
    product_id BIGINT    NOT NULL,
    quantity   INTEGER   NOT NULL CHECK (quantity >= 1),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cart_id)    REFERENCES cart(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    UNIQUE (cart_id, product_id)
);

-- orders
CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT         NOT NULL,
    total_amount     DECIMAL(19,2)  NOT NULL,
    status           VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    shipping_address VARCHAR(200)   NOT NULL,
    created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES member(id)
);

-- order_item (snapshots product name and price at time of order)
CREATE TABLE order_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(255)   NOT NULL,
    quantity     INTEGER        NOT NULL CHECK (quantity >= 1),
    unit_price   DECIMAL(19,2)  NOT NULL,
    FOREIGN KEY (order_id)   REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);
